Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "mirror.sistema.sol"

  config.vm.network "private_network", ip: "192.168.56.20"

  config.vm.provision "shell", path: "provision.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "mirror.sistema.sol"
    vb.memory = 512
    vb.cpus = 1
  end
end
