Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.hostname = "ftp.sistema.sol"

  config.vm.network "private_network", ip: "192.168.56.30"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "FTP-Seguro"
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.provision "shell", path: "provision.sh"
end
