Vagrant.configure("2") do |config|

  # =========================
  # SERVIDOR FTP
  # =========================
  config.vm.define "ftpserver" do |srv|
    srv.vm.box = "debian/bookworm64"
    srv.vm.hostname = "ftp.sistema.sol"
    srv.vm.network "private_network", ip: "192.168.56.30"

    srv.vm.provider "virtualbox" do |vb|
      vb.name = "FTP-Servidor"
      vb.memory = 1024
    end

    srv.vm.provision "shell", path: "provision-servidor.sh"
  end

  # =========================
  # CLIENTE FTP
  # =========================
  config.vm.define "ftpcliente" do |cli|
    cli.vm.box = "debian/bookworm64"
    cli.vm.hostname = "cliente"
    cli.vm.network "private_network", ip: "192.168.56.40"

    cli.vm.provider "virtualbox" do |vb|
      vb.name = "FTP-Cliente"
      vb.memory = 512
    end

    cli.vm.provision "shell", path: "provision-cliente.sh"
  end

end
